CREATE DATABASE MTS_ecosystems;

CREATE TABLE interval_trees_of_the_elements (
    ID INT PRIMARY KEY NOT NULL, -- AUTO_INCREMENT removed to remove an error message.
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    POSITION SMALLINT NOT NULL,
    PARENT_ID INT NOT NULL,
    CREATED_DATE  DATETIME NOT NULL default CURRENT_TIMESTAMP,
    UPDATED_DATE  DATETIME NULL,
    INTERVAL_INPUT INT NOT NULL,
    INTERVAL_OUTPUT INT NOT NULL,
    TREE_LEVEL SMALLINT NOT NULL,
    FILE_ID INT NOT NULL
);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title0','',0,0,1,13,0,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title1','',2,1,2,3,1,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title2','',4,1,4,5,1,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title3','',6,1,11,12,1,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title2.1','',2,3,5,6,2,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title2.2','',4,3,7,8,2,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title2.3','',6,3,9,10,2,111);







INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title0','',0,0,20,25,0,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title0','',0,0,21,22,0,111);

INSERT INTO MTS_ecosystems.interval_trees_of_the_elements (TITLE,DESCRIPTION,POSITION,PARENT_ID,INTERVAL_INPUT,INTERVAL_OUTPUT,TREE_LEVEL,FILE_ID)
    VALUES ('title0','',0,0,23,24,0,111);

